#!/bin/bash

function read_and_commit {
    read -rp "Commit Message: " MESSAGE
    git c -m "$MESSAGE"
}

com_push_flag=$(echo $1 | tr -d "\-a")

if ! (test -z $com_push_flag || test $com_push_flag = o || test $com_push_flag = n); then
    echo 'Unknown flag '"$com_push_flag"'; use -n or -o'
    exit
fi

if echo $1 | rg a > /dev/null; then
    echo Adding all to index
    git add .
fi

echo $com_push_flag

case $com_push_flag in
    n)
        echo Amending HEAD with no edit
        git can
        git p -f
        ;;
    o)
        read_and_commit
        echo Pushing and setting upstream to origin
        git puo $(git rev-parse --abbrev-ref HEAD)
        ;;
    *)
        read_and_commit
        echo Pushing
        git p
        ;;
esac

