#! /bin/zsh
#
# This script runs every 30 mins or whatever duration is specified in "crontab -l".
#
# Its purpose is to push a notification when the Akasha Pizza Heaven store is open for orders.
#
# 1. Validate that the store has not been confirmed open for the day. 
# 2. Query DotPe endpoint to retrieve store config.
# 3. storeStatusFlag == true?
# 4. Notify.
# 5. Make entry into log for subsequent validation checks.
#
# akasha.log will be used for validation.
# This file will be overwritten daily since
# there's no need to maintain a log and the
# validation is a simple daily check for the date.
#
# grep has been used in place of the malfunctioning rg.
# Potential RCA: https://github.com/BurntSushi/ripgrep/discussions/1979.

grep $(date "+%Y-%m-%d") /Users/ritwik/logs/akasha.log > /dev/null 2>&1 && exit

curl -s "https://api.dotpe.in/api/merchant/external/cstore/1?referer=akashapizzaheaven&serviceSubtype=delivery" | \
    [[ $(grep -o "storeStatusFlag[^,]*") =~ "true" ]] && \
    osascript -e 'display notification "OPEN" with title "Akasha Pizza Heaven" sound name "Submarine"' && \
    echo $(date "+%Y-%m-%d") > /Users/ritwik/logs/akasha.log
