#! /bin/bash

# if [ -z "$1" -o -z "$2" ] && [ $1 != "list" ];
if [ "$1" != "list" -a -z "$2" ]
then
    echo "This script requires 2 arguments: the action name and the object name."
    exit 1
fi

TMP=$(mktemp)

case "$1" in

    get)
        aws s3api get-object --bucket $AWS_VAULT_BUCKET --key "$2" "$TMP"
        bat $TMP
        rm $TMP;;

    put) aws s3api put-object --bucket $AWS_VAULT_BUCKET --key "$2" --body "$2" ;;

    list) aws s3api list-objects --bucket $AWS_VAULT_BUCKET ;;

esac

