#!/bin/bash

if (echo "$1" | rg ritwik > /dev/null); then
    REPO=dotfiles
else
    REPO=bin
fi

if (test $REPO = bin); then
    FILE=$(echo $1 | rg -o "[^/]*$")
else
    FILE=$(echo $1 | sed -e "s/\/Users\/ritwik\///")
fi

ENDPOINT="https://api.github.com/repos/ritwikvd/$REPO/contents/$FILE"
ENCODED_CONTENT=$(base64 -i $1)
FILE_SHA=$(curl -s $ENDPOINT | rg sha | cut -d':' -f 2 | tr -d ' ,"')

echo "%{http_code}" -X PUT -H "Accept: application/vnd.github.v3+json" -H "Authorization: bearer $DOTFILES_TOKEN" $ENDPOINT -d '{"message": "Synchronising from up", "sha": "'$FILE_SHA'", "content": "'$ENCODED_CONTENT'"}'
STATUS_CODE=$(curl -o /dev/null -w "%{http_code}" -X PUT -H "Accept: application/vnd.github.v3+json" -H "Authorization: bearer $DOTFILES_TOKEN" $ENDPOINT -d '{"message": "Synchronising from up", "sha": "'$FILE_SHA'", "content": "'$ENCODED_CONTENT'"}' | rg -o "\d*")

osascript -e 'display notification "Pushed to '$REPO' with response: '$STATUS_CODE'" with title "Autocmd Update: '$FILE'" sound name "Submarine"'
