#!/bin/bash

if (echo "$1" | rg ritwik); then
    REPO=dotfiles
else
    REPO=bin
fi
echo this is the repo
echo $REPO

if test $REPO==bin; then
    FILE=$(echo $1 | rg -o "[^/]*$")
    echo inside bin
else
    FILE=$(echo $1 | sed -e "s/\/Users\/ritwik\///")
    echo inside dotfiles
fi

ENDPOINT="https://api.github.com/repos/ritwikvd/$REPO/contents/$FILE"
ENCODED_CONTENT=$(base64 $1)
FILE_SHA=$(curl -s $ENDPOINT | grep sha | cut -d':' -f 2 | tr -d ' ,"')

STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X PUT -H "Accept: application/vnd.github.v3+json" -H "Authorization: bearer $DOTFILES_TOKEN" $ENDPOINT -d '{"message": "Synchronising from up", "sha": "'$FILE_SHA'", "content": "'$ENCODED_CONTENT'"}' | grep -o "\d*")

osascript -e 'display notification "Pushed to '$REPO' with response: '$STATUS_CODE'" with title "Autocmd Update: '$FILE'" sound name "Submarine"'
