#!/bin/bash

file=$1 #This will be either .gitconfig/.zshrc/.prettierrc/.vimrc
endpoint="https://api.github.com/repos/ritwikvd/dotfiles/contents/$file"
encoded_content=$(base64 ~/$file)
file_sha=$(curl -s $endpoint | grep sha | cut -d':' -f 2 | tr -d ' ,"')

status_code=$(curl -s -o /dev/null -w "%{http_code}" -X PUT -H "Accept: application/vnd.github.v3+json" -H "Authorization: bearer $DOTFILES_TOKEN" $endpoint -d '{"message": "Synchronising from updotfiles", "sha": "'$file_sha'", "content": "'$encoded_content'"}' | grep -o "\d*")

osascript -e 'display notification "Pushed to dotfiles with response: '$status_code'" with title "Autocmd Update: '$file'" sound name "Submarine"'
